# This file has very loose rules to allow the template folder to not have warnings.
include: package:lint/analysis_options.yaml

linter:
  rules:
    
    avoid_print: false
    avoid_relative_lib_imports: false
    