name: dockerize_template_folder
description: Pubspec to manage the dependencies of the template folder
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dcli: ^1.36.0
  dockerize_sidekick_plugin:
    path: ../
  shelf: ^1.4.0
  shelf_helmet: ^1.1.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.0
  sidekick_core: ^0.15.1

dev_dependencies: 
  lint: '>=1.7.0 <2.0.0'
