name: dockerize_sidekick_plugin
description: Lets you easily generate a Docker Container for your Flutter Web App.
version: 0.1.0
repository: https://github.com/jxstxn1/dockerize_sidekick_plugin/tree/main
issue_tracker: https://github.com/jxstxn1/dockerize_sidekick_plugin/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.36.0
  sidekick_core: '>=0.7.1 <1.0.0'

dev_dependencies:
  lint: ^2.0.0
  sidekick_plugin_installer: ^0.2.1

  # Template Dependencies
  shelf_static: ^1.1.0
  shelf_router: ^1.1.3
  shelf_helmet: ^1.1.0