name: dockerize_sidekick_plugin
description: Generate a Docker Container for your Flutter Web App
version: 0.1.0
repository: https://github.com/jxstxn1/dockerize_sidekick_plugin/tree/main
issue_tracker: https://github.com/jxstxn1/dockerize_sidekick_plugin/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.36.0
  sidekick_core: '>=0.7.1 <1.0.0'

dev_dependencies:
  lint: ^1.5.0
  sidekick_plugin_installer: ^0.1.3
