name: dockerize_sidekick_plugin
description: Lets you easily generate a Docker Container for your Flutter Web App.
version: 0.4.0
repository: https://github.com/jxstxn1/dockerize_sidekick_plugin/tree/main
issue_tracker: https://github.com/jxstxn1/dockerize_sidekick_plugin/issues

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  html: ^0.15.1
  mason_logger: ^0.2.3
  path: ^1.8.3
  sidekick_core: ^1.0.1
  stream_transform: ^2.1.0
  watcher: ^1.0.2

dev_dependencies:
  lint: '>=1.7.0 <2.0.0'
  mocktail: ^0.3.0
  sidekick_plugin_installer: ^0.3.0
  test: ^1.22.0
