name: dockerize_sidekick_plugin
description: Lets you easily generate a Docker Container for your Flutter Web App.
version: 0.8.0
repository: https://github.com/jxstxn1/dockerize/tree/main/dockerize_sidekick_plugin/
issue_tracker: https://github.com/jxstxn1/dockerize/issues

topics:
  - sidekick
  - cli
  - docker
  - sidekick-plugin
  - flutter-web

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.2
  # TODO: replace as soon as dockerize_data is published
  dockerize_data:
    path: ../dockerize_data
  html: ^0.15.1
  mason_logger: ^0.2.3
  path: ^1.8.3
  sidekick_core: ^2.0.0
  stream_transform: ^2.1.0
  watcher: ^1.0.2

dev_dependencies:
  lint: ^2.0.0
  mocktail: ^0.3.0
  sidekick_plugin_installer: ^1.1.0
  test: ^1.24.0
